### ISSUE TITLE
kpt: failed to execute preStop hook

### ISSUE THREAD

**Issue by 110y** [110y/bootes#74]
```
preStop:
  exec:
    command:
    - sh
    - -c
    - sleep 5
```

`preStop` executes `sh -c sleep 5`, however distroless image does not have such commands.
